import Link from "next/link";
import { useEffect, useState } from "react";
import { useData } from "../../hooks/custom-hooks";
import rest from "../../utils/rest";
import Swal from "sweetalert2";
import { useRouter } from "next/router";
import { showError } from "../../utils/alert";
import Head from "next/head";
import config from "../../appconfig.json";

const initState = {
  companyid: "",
  companyname: "",
};

export default function CompanyForm() {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [state, setState] = useData(initState);

  useEffect(() => {
    const companyid = localStorage.getItem("companyid");
    if (companyid) {
      Swal.fire({
        showConfirmButton: false,
        title: "Please Wait !",
        html: `<div style="width: 5rem; height: 5rem;" className="spinner-border m-3 text-info" role="status">
                <span className="visually-hidden">Loading...</span>
              </div>`,
        // add html attribute if you want or remove
        allowOutsideClick: false,
        onBeforeOpen: () => {
          Swal.showLoading();
        },
      });
      rest.get(`/companies/${companyid}`).then(([data, err]) => {
        Swal.close();
        if (err) {
          showError(err);
        } else {
          setState(data.data.data);
        }
      });
    }
  }, []);

  const handleNew = () => {
    localStorage.setItem("companyid", "");
    setState(initState);
  };

  const handleSave = async () => {
    if (loading) return;
    setLoading(true);
    Swal.fire({
      showConfirmButton: false,
      title: "Please Wait !",
      html: `<div style="width: 5rem; height: 5rem;" className="spinner-border m-3 text-info" role="status">
          <span className="visually-hidden">Loading...</span>
        </div>`,
      // add html attribute if you want or remove
      allowOutsideClick: false,
      onBeforeOpen: () => {
        Swal.showLoading();
      },
    });

    const body = { ...state };
    let promise;
    const companyid = localStorage.getItem("companyid");
    if (companyid) {
      promise = rest.put(`/companies/${companyid}`, body);
    } else {
      if (body.hasOwnProperty("id")) {
        delete body.id;
      }
      promise = rest.post("/companies", body);
    }
    const [data, error] = await promise;
    if (error) {
      Swal.close();
      showError(err);
    }
    if (data) {
      Swal.close();

      Swal.fire({
        position: "center",
        icon: "success",
        title: data.data.message,
        showConfirmButton: false,
        timer: 5000,
      });

      if (!companyid) {
        setState({
          ...data.data.data,
        });
        localStorage.setItem("companyid", data.data.data.companyid);
      }
    }
    setLoading(false);
  };

  const confirmDelete = (companyid) => {
    const swalWithBootstrapButtons = Swal.mixin({
      customClass: {
        confirmButton: "btn btn-success mx-2",
        cancelButton: "btn btn-danger mx-2",
      },
      buttonsStyling: false,
    });

    swalWithBootstrapButtons
      .fire({
        title: "Are you sure?",
        text: "You won't be able to revert this!",
        icon: "warning",
        showCancelButton: true,
        confirmButtonText: "Yes, delete it!",
        cancelButtonText: "No, cancel!",
        reverseButtons: true,
      })
      .then((result) => {
        if (result.isConfirmed) {
          Swal.fire({
            showConfirmButton: false,
            title: "Please Wait !",
            html: `<div style="width: 5rem; height: 5rem;" className="spinner-border m-3 text-info" role="status">
                    <span className="visually-hidden">Loading...</span>
                  </div>`,
            // add html attribute if you want or remove
            allowOutsideClick: false,
            onBeforeOpen: () => {
              Swal.showLoading();
            },
          });
          rest.delete(`/companies/${companyid}`).then(([data, err]) => {
            Swal.close();
            if (err) {
              showError(err);
            } else {
              swalWithBootstrapButtons
                .fire("Deleted!", "Your data has been deleted.", "success")
                .then(() => {
                  router.push("/company");
                });
            }
          });
        } else if (
          /* Read more about handling dismissals below */
          result.dismiss === Swal.DismissReason.cancel
        ) {
          swalWithBootstrapButtons.fire(
            "Cancelled",
            "Your data is safe :)",
            "error"
          );
        }
      });
  };

  return (
    <div style={{ marginBottom: "4rem" }}>
      <Head>
        <title>{config.version}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav
        style={{
          "--bs-breadcrumb-divider": "'>'",
        }}
        aria-label="breadcrumb"
      >
        <ol className="breadcrumb">
          <li className="breadcrumb-item">
            <Link href="/company">
              <a>Company Setup</a>
            </Link>
          </li>
          <li className="breadcrumb-item active" aria-current="page">
            {state.companyid ? state.companyid : "New"}
          </li>
        </ol>
      </nav>

      <div className="card" style={{ minHeight: "550px" }}>
        <div className="card-body">
          <div className="row mb-4">
            <div className="col-xl-4">
              <button
                className="btn btn-primary mx-2"
                style={{ marginLeft: "0px!important" }}
                onClick={handleNew}
              >
                New
              </button>
              <button
                disabled={!state.companyname}
                className="btn btn-success mx-2"
                onClick={handleSave}
              >
                {state.companyid ? "Update" : "Save"}
              </button>
              <button
                disabled={!state.companyid}
                onClick={confirmDelete.bind(this, state.companyid)}
                className="btn btn-danger mx-2"
              >
                Delete
              </button>
            </div>
            <div className="col-xl-1"></div>
            <div className="col-xl-1"></div>
          </div>

          <div className="row mb-3">
            <div className="col-xl-4">
              <label className="form-label">ID</label>
              <input
                type="text"
                readOnly
                className="form-control"
                value={state.companyid}
                onChange={(e) => setState({ companyid: e.target.value })}
              />
            </div>
          </div>
          <div className="row mb-3">
            <div className="col-xl-4">
              <label className="form-label">Name</label>
              <input
                type="text"
                className="form-control required-field"
                value={state.companyname}
                onChange={(e) => setState({ companyname: e.target.value })}
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
