import Head from "next/head";
import { useEffect } from "react";
import { useData } from "../hooks/custom-hooks";
import styles from "../styles/Home.module.css";
import config from "../appconfig.json";

const initState = {
  username: "",
};

export default function Home() {
  const [state, setState] = useData(initState);

  useEffect(() => {
    const username = localStorage.getItem("username");
    setState({ username });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>{config.version}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>
        <span style={{ fontWeight: "bold", fontSize: "2.3rem" }}>Hi</span>,{" "}
        <span style={{ fontSize: "2rem" }}>{state.username}</span>
      </h1>
    </div>
  );
}
